import pandas as pd
from pathlib import Path
from dataclasses import dataclass
import re

def get_files(dat_file):
    dat_file = Path(dat_file)
    ts_files = []
    pr_file = None

    for f in dat_file.parent.glob(f'{dat_file.stem}*'):
        if re.match('\.[0-9]$|\.dat$',f.suffix):
            ts_files.append(f)
        elif f.suffix == '.mpr':
            pr_file = f

    return ts_files, pr_file

def read_tsv_with_comments(file):
    data = []
    comment_buffer = []
    timestamp = ''
    with open(file, 'r') as file:
        for line in file:
            line = line.strip()

            if not line:
                continue

            if line.startswith('#'):
                clean_comment = line.lstrip('#').strip()
                comment_buffer.append(clean_comment)
            else:
                timestamp, value = line.split('\t')

                meta = " ".join(comment_buffer)

                data.append({
                    'timestamp': timestamp,
                    'value': float(value),
                    'comment': meta
                })

                comment_buffer = []
    
    return data

def read_timeseries_files(ts_files):
    # order files by suffix [.dat, .0, ..., .n]
    ts_files = sorted(ts_files, key=lambda x: (0 if x.suffix == '.dat' else int(x.suffix[1:] ) + 1))

    # load files, adding any blocks prepended with # to a new column 'meta'
    data = []
    for f in ts_files:
        data.extend(read_tsv_with_comments(f))

    data = pd.DataFrame(data)

    data['timestamp'] = pd.to_datetime(data['timestamp'], format='%d/%m/%Y %H:%M:%S.%f')

    return data

def parse_line(line):
    profile, reading, position, date, time, value = line.split('\t')

    return {
        'auto-profile': int(profile),
        'reading': int(reading),
        'position': float(position),
        'timestamp': date + ' ' + time,
        'value': float(value),
        'comment': ''
    }


@dataclass
class OxygenProfile:
    meta: list
    data: pd.DataFrame

    def __repr__(self):
        out = []
        out.append(f'OxygenProfile with {len(self.data)} readings')
        out.append('\n'.join(self.meta[:-1]))
        return '\n'.join(out)

def read_profile_file(pr_file, start_marker='Data generated by m-Profiler server'):

    data_blocks = []
    with open(pr_file, 'r') as file:
        block = None
        meta = []
        header = False
        for line in file:
            line = line.strip()
            comment_buffer = []
            if start_marker in line:
                if block:
                    data_blocks.append(block)
                block = {'data': [], 'meta': []}
                meta = []
                header = True
            else:
                if header:
                    if line.startswith('#'):
                        clean_comment = line.lstrip('#').strip()
                        meta.append(clean_comment)
                    elif line:
                        header = False
                        block['meta'] = meta
                        block['data'].append(parse_line(line))
                else:
                    if line.startswith('#'):
                        clean_comment = line.lstrip('#').strip()
                        comment_buffer.append(clean_comment)
                    else:
                        out = parse_line(line)
                        out['comment'] = " ".join(comment_buffer)
                        block['data'].append(out)

                        comment_buffer = []
        if block:
            data_blocks.append(block)

    return [OxygenProfile(meta=b['meta'], data=pd.DataFrame(b['data'])) for b in data_blocks]
